using UnityEngine;


public class PlayerMicNoiseEmitter : MonoBehaviour
{
    [Header("Noise Mapping")]
    [Tooltip("Extra dB above noise floor required to count as speaking.")]
    public float speakingMarginDb = 15f;

    [Tooltip("Meters of reach at the threshold.")]
    public float baseLoudnessMeters = 6f;

    [Tooltip("Extra meters per 10dB above threshold.")]
    public float loudnessPer10dB = 4f;

    [Header("Dynamic Threshold")]
    [Tooltip("How fast the noise floor adapts (seconds). Higher = slower")]
    public float noiseFloorAdaptTime = 3f;

    [Tooltip("Minimum allowed noise floor (safety clamp).")]
    public float minNoiseFloorDb = -70f;

    [Tooltip("Maximum allowed noise floor (prevents abuse).")]
    public float maxNoiseFloorDb = -30f;

    [Header("Cadence")]
    [Tooltip("Seconds between noise events.")]
    public float minEmitInterval = 0.15f;

    [Header("Refs")]
    [Tooltip("Player Cam (to know where to emit sound from)")]
    public Transform head;


    [Header("Debug Overlay")] //Debug generated with ChatGPT
    public bool showOverlay = true;
    public Vector2 overlayPos = new Vector2(20, 50);
    public Vector2 overlaySize = new Vector2(260, 18);

    [Header("Locker / Occlusion")]
    [HideInInspector] public float occlusionMultiplier = 1f;

    [Header("Vent Redirect (voice into duct)")]
    [Tooltip("If set, voice noise is emitted at this transform as well (vent exit).")]
    public Transform voiceRedirectTarget = null;

    [Tooltip("Multiplier for noise at vent exit (remote). 1 = same loudness as normal.")]
    public float ventRemoteMultiplier = 1.0f;

    [Tooltip("Multiplier for noise at player position when talking into vent. <1 = quieter locally.")]
    public float ventLocalMultiplier = 0.4f;

    // timers
    private float _timer;
    private float _displayedDb;

    // public readings
    public float currentDbFS { get; private set; } = -80f;
    public float currentPeak { get; private set; } = 0f;

    // dynamic noise floor
    private float _noiseFloorDb = -60f;
    private bool _noiseFloorInitialized = false;

    private void Start()
    {
#pragma warning disable CS0618
        var voiceProcessor = FindObjectOfType<VoiceProcessor>();
#pragma warning restore CS0618

        if (voiceProcessor != null)
        {
            voiceProcessor.OnFrameCapturedRaw += OnVoiceFrame;
        }
        else
        {
            Debug.LogWarning("[MicEmitter] No VoiceProcessor found!");
        }
    }

    private void OnDestroy()
    {
#pragma warning disable CS0618
        var voiceProcessor = FindObjectOfType<VoiceProcessor>();
#pragma warning restore CS0618

        if (voiceProcessor != null)
        {
            voiceProcessor.OnFrameCapturedRaw -= OnVoiceFrame;
        }
    }

    private void Update()
    {
        // Smooth debug overlay only. Generated by ChatGPT
        _displayedDb = Mathf.Lerp(
            _displayedDb,
            currentDbFS,
            1f - Mathf.Exp(-10f * Time.deltaTime)
        );

        _timer += Time.deltaTime;

        float dynamicThreshold = _noiseFloorDb + speakingMarginDb;

        if (_timer >= minEmitInterval && currentDbFS > dynamicThreshold)
        {
            Vector3 headPos = head ? head.position : transform.position + Vector3.up * 1.6f;
            Vector3 feetPos = transform.position + Vector3.up * 0.05f;

            // Mute inside safe zones
            if (!(SafeAreaVolume.IsPointInside(headPos) || SafeAreaVolume.IsPointInside(feetPos)))
            {
                float metersBase =
                    baseLoudnessMeters +
                    Mathf.Max(
                        0f,
                        (currentDbFS - dynamicThreshold) / 10f * loudnessPer10dB
                    );

                if (voiceRedirectTarget != null)
                {
                    float remoteMeters = metersBase * Mathf.Max(0f, ventRemoteMultiplier);
                    float localMeters = metersBase * Mathf.Max(0f, ventLocalMultiplier) * occlusionMultiplier;

                    Noise.MakeNoise(voiceRedirectTarget.position, remoteMeters, gameObject);

                    if (localMeters > 0.01f)
                        Noise.MakeNoise(headPos, localMeters, gameObject);
                }
                else
                {
                    float meters = metersBase * occlusionMultiplier;
                    Noise.MakeNoise(headPos, meters, gameObject);
                }
            }

            _timer = 0f;
        }
    }

 
    private void OnVoiceFrame(short[] pcmBuffer)
    {
        if (pcmBuffer == null || pcmBuffer.Length == 0)
        {
            currentDbFS = -80f;
            currentPeak = 0f;
            return;
        }

        double sum = 0.0;
        float peak = 0f;

        for (int i = 0; i < pcmBuffer.Length; i++)
        {
            float s = pcmBuffer[i] / (float)short.MaxValue; //generated with ChatGPT
            sum += s * s;
            float a = Mathf.Abs(s);
            if (a > peak) peak = a;
        }

        float rms = Mathf.Sqrt((float)(sum / pcmBuffer.Length));

        currentPeak = peak;
        currentDbFS = Mathf.Clamp(
            20f * Mathf.Log10(Mathf.Max(1e-6f, rms)),
            -80f,
            0f
        );

        UpdateNoiseFloor(currentDbFS);
    }

    private void UpdateNoiseFloor(float db)
    {
        float currentThreshold = _noiseFloorDb + speakingMarginDb;

        // Ignore speech spikes
        if (_noiseFloorInitialized && db > currentThreshold)
            return;

        if (!_noiseFloorInitialized)
        {
            _noiseFloorDb = db;
            _noiseFloorInitialized = true;
            return;
        }

        float alpha = 1f - Mathf.Exp(
            -Time.deltaTime / Mathf.Max(0.01f, noiseFloorAdaptTime)
        );

        _noiseFloorDb = Mathf.Lerp(_noiseFloorDb, db, alpha);
        _noiseFloorDb = Mathf.Clamp(_noiseFloorDb, minNoiseFloorDb, maxNoiseFloorDb);
    }

    private static Texture2D _solidTex; //generated with ChatGPT

private static Texture2D SolidTex //method generated with ChatGPT
{
    get
    {
        if (_solidTex == null)
        {
            _solidTex = new Texture2D(1, 1, TextureFormat.RGBA32, false);
            _solidTex.SetPixel(0, 0, Color.white);
            _solidTex.Apply();
        }
        return _solidTex;
    }
}

private void OnGUI()//method generated with ChatGPT
{
    if (!showOverlay) return;

    var rect = new Rect(overlayPos.x, overlayPos.y, overlaySize.x, overlaySize.y);
    float t = Mathf.InverseLerp(-80f, 10f, _displayedDb);

    Color old = GUI.color;

    // Background (solid black w/ alpha)
    GUI.color = new Color(0f, 0f, 0f, 0.55f);
    GUI.DrawTexture(rect, SolidTex);

    // Fill (solid white w/ alpha)
    var fillRect = new Rect(rect.x, rect.y, rect.width * Mathf.Clamp01(t), rect.height);
    GUI.color = new Color(1f, 1f, 1f, 0.9f);
    GUI.DrawTexture(fillRect, SolidTex);

    GUI.color = Color.black;
    GUI.Label(new Rect(rect.x + 6, rect.y - 18, rect.width, 18), "Mic: adaptive threshold");
    GUI.Label(new Rect(rect.x + 6, rect.y + 2, rect.width, rect.height),
        $"{_displayedDb:0.0} dBFS | floor {_noiseFloorDb:0.0} | thresh {(_noiseFloorDb + speakingMarginDb):0.0}");

    GUI.color = old;
}

}
