using System.Collections;
using UnityEngine;
using UnityEngine.AI;

public class DoorSlideUp : MonoBehaviour
{
    [Header("Door ID")]
    [Tooltip("Unique door name, e.g. A-45, A-12, etc.")]
    public string doorId = "A-01";

    [Header("Mission Events (optional)")]
    [SerializeField] private bool raiseMissionEvents = true;

    [Header("Locking")]
    [SerializeField] private bool startLocked = false;

    [Header("NavMesh (AI blocking)")]
    [SerializeField] private NavMeshObstacle navObstacle;

    
    [SerializeField] private bool lockedAlwaysBlocks = false;

    
    private bool isLocked;

    public bool IsLocked => isLocked;
    public bool IsOpen => isOpen;
    public bool ManualOverride => manualOverride;

    [Header("References")]
    [SerializeField] private Transform panel;                // moving part
    [SerializeField] private BoxCollider blockingCheck;      // volume to test for safe closing

    [Header("Motion")]
    [SerializeField] private float openOffsetY = 2.2f;       // how high to lift the panel
    [SerializeField] private float openTime = 0.752f;        // seconds to fully open
    [SerializeField] private float closeTime = 0.60f;        // seconds to fully close

    [SerializeField] private float closeDelay = 0.8f;        // wait after last actor leaves
    [SerializeField] private bool manualOverride = false;

    [Header("Filtering")]
    [SerializeField] private LayerMask actorMask = ~0;       // who triggers the door

    [Header("SFX")]
    [SerializeField] private AudioSource openOneShot;
    [SerializeField] private AudioSource closeOneShot;
    [SerializeField] private AudioSource movingLoop;         

    [Header("Small Actor Opening (Roombas)")]
    [SerializeField] private bool enableSmallOpen = true;

    [Tooltip("Roombas mask).")]
    [SerializeField] private LayerMask smallActorMask;

    [Tooltip("How high the door opens for Roombas")]
    [SerializeField] private float smallOpenOffsetY = 0.9f;

    [Tooltip("opening speed for roombas")]
    [SerializeField] private float smallOpenTime = 0.45f;

    [Header("Indicator Light (optional)")]
    [SerializeField] private Light indicatorLight;

    [Tooltip("Color when sensor control is active (manualOverride = false).")]
    [SerializeField] private Color sensorColor = Color.green;

    [Tooltip("Color when manual override is active AND door is closed.")]
    [SerializeField] private Color manualClosedColor = new Color(1f, 0.5f, 0f); // orange

    [Tooltip("Color when door is locked (overrides all other states).")]
    [SerializeField] private Color lockedColor = Color.red;

    // Runtime
    private Vector3 closedLocalPos;
    private Vector3 openLocalPos;
    private Vector3 smallOpenLocalPos;
    private bool openedFullThisCycle = false; // once we open full, don't downgrade until it closes

    private readonly System.Collections.Generic.HashSet<Collider> occupants = new();
    private int OccupantCount => occupants.Count;

    private Coroutine animRoutine;
    private Coroutine pendingCloseRoutine;
    private bool isOpen = false;



   
    public void OpenDoor()
    {
        if (isLocked) return;

        manualOverride = true;

        if (pendingCloseRoutine != null)
        {
            StopCoroutine(pendingCloseRoutine);
            pendingCloseRoutine = null;
        }

        OpenNow();
        UpdateNavObstacle(); // //method generated by ChatGPT
    }

    public string NormalizedId => DoorRegistry.NormalizeDoorId(doorId);

    private void OnEnable()
    {
        DoorRegistry.Register(this);
    }

    private void OnDisable()
    {
        DoorRegistry.Unregister(this);
    }

    public void CloseDoor()
    {
        if (isLocked) return;

        manualOverride = true;

        if (pendingCloseRoutine != null)
        {
            StopCoroutine(pendingCloseRoutine);
            pendingCloseRoutine = null;
        }

        UpdateNavObstacle(); //method generated by ChatGPT

        if (SafeToClose())
            StartMove(closedLocalPos, closeTime, false);
        else
            ScheduleClose();
    }

  
    public void EnableSensorControl()
    {
        manualOverride = false;
        UpdateNavObstacle(); // //method generated by ChatGPT
    }


    public void ToggleDoor()
    {
        if (isLocked) return;

        if (isOpen) CloseDoor();
        else OpenDoor();
    }

    private void Reset() //method generated by ChatGPT
    {
        // Try to auto-assign panel/box from children
        if (panel == null && transform.childCount > 0) panel = transform.GetChild(0);
        if (blockingCheck == null) blockingCheck = GetComponentInChildren<BoxCollider>();

        // Try to auto-assign an indicator light from children (optional)
        if (indicatorLight == null) indicatorLight = GetComponentInChildren<Light>(true);
    }

    private void Awake()
    {
        if (panel == null)
        {
            Debug.LogError("[DoorSlideUp] Panel not assigned.", this);
            enabled = false;
            return;
        }

        if (navObstacle == null)
            navObstacle = GetComponentInChildren<NavMeshObstacle>(true);
        if (indicatorLight == null)
            indicatorLight = GetComponentInChildren<Light>(true);

        closedLocalPos = panel.localPosition;
        openLocalPos = closedLocalPos + Vector3.up * openOffsetY;

        isLocked = startLocked;
        smallOpenLocalPos = closedLocalPos + Vector3.up * Mathf.Min(smallOpenOffsetY, openOffsetY);

        UpdateNavObstacle(); //method generated by ChatGPT
    }

    private bool IsSmallActor(GameObject go) //method generated by ChatGPT
    {
        if (!enableSmallOpen) return false;

        // LayerMask check
        if ((smallActorMask.value & (1 << go.layer)) != 0)
            return true;

        // Optional: also treat anything with a Roomba script as small (safe fallback)
        if (go.GetComponentInParent<RoombaPatrolAndVision>() != null)
            return true;

        return false;
    }

    public void SensorEnter(Collider other)
    {
        if (manualOverride) return;
        if (!IsActor(other.gameObject)) return;

        bool added = occupants.Add(other);

        if (isLocked) return;

        bool small = IsSmallActor(other.gameObject);

        if (added && OccupantCount == 1)
        {
            openedFullThisCycle = !small;
            OpenNowTo(small ? smallOpenLocalPos : openLocalPos,
                      small ? smallOpenTime : openTime);
            return;
        }

        if (!small && !openedFullThisCycle)
        {
            openedFullThisCycle = true;
            OpenNowTo(openLocalPos, openTime);
        }
    }

    public void SensorExit(Collider other)
    {
        if (manualOverride) return;
        if (!IsActor(other.gameObject)) return;

        occupants.Remove(other);

        if (isLocked) return;

        if (OccupantCount == 0) ScheduleClose();
    }


    private void OpenNowTo(Vector3 targetLocal, float duration)
    {
        if (isLocked) return;

        if (pendingCloseRoutine != null)
        {
            StopCoroutine(pendingCloseRoutine);
            pendingCloseRoutine = null;
        }

        StartMove(targetLocal, duration, true);
    }



    private bool IsActor(GameObject go)
    {
        return (actorMask.value & (1 << go.layer)) != 0;
    }

    private void OpenNow()
    {
        OpenNowTo(openLocalPos, openTime);
    }

    private void ScheduleClose()
    {
        if (isLocked) return;

        if (pendingCloseRoutine != null) return;
        pendingCloseRoutine = StartCoroutine(CloseAfterDelay());
    }

    private IEnumerator CloseAfterDelay()
    {
        if (isLocked) yield break;

        yield return new WaitForSeconds(closeDelay);

        if (!SafeToClose())
            yield return new WaitUntil(() => SafeToClose());

        StartMove(closedLocalPos, closeTime, false);

        pendingCloseRoutine = null;
    }

    private bool SafeToClose() //method generated by ChatGPT
    {
        if (blockingCheck == null) return true;

        var worldCenter = blockingCheck.transform.TransformPoint(blockingCheck.center);
        var worldHalfExtents = Vector3.Scale(blockingCheck.size * 0.5f, blockingCheck.transform.lossyScale);

        Collider[] hits = Physics.OverlapBox(
            worldCenter,
            worldHalfExtents,
            blockingCheck.transform.rotation,
            actorMask,
            QueryTriggerInteraction.Ignore
        );

        return hits == null || hits.Length == 0;
    }

    public void LockDoor()
    {
        isLocked = true;
        UpdateNavObstacle(); //method generated by ChatGPT
    }

    public void UnlockDoor()
    {
        isLocked = false;
        UpdateNavObstacle(); //method generated by ChatGPT
    }

    public void SetLocked(bool locked)
    {
        isLocked = locked;
        UpdateNavObstacle(); //method generated by ChatGPT
    }

    private void StartMove(Vector3 targetLocal, float duration, bool opening)
    {
        if (opening) { if (openOneShot) openOneShot.Play(); }
        else { if (closeOneShot) closeOneShot.Play(); }

        if (movingLoop)
        {
            movingLoop.loop = true;
            if (!movingLoop.isPlaying) movingLoop.Play();
        }

        if (animRoutine != null) StopCoroutine(animRoutine);
        animRoutine = StartCoroutine(MovePanel(targetLocal, duration, opening));
    }

    private IEnumerator MovePanel(Vector3 targetLocal, float duration, bool opening)
    {
        isOpen = opening;
        UpdateNavObstacle(); //method generated by ChatGPT

        Vector3 startLocal = panel.localPosition;

        if (duration <= 0f)
        {
            panel.localPosition = targetLocal;
        }
        else
        {
            float elapsed = 0f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float t = Mathf.Clamp01(elapsed / duration);
                t = Mathf.SmoothStep(0f, 1f, t);

                panel.localPosition = Vector3.Lerp(startLocal, targetLocal, t);
                yield return null;
            }

            panel.localPosition = targetLocal;
        }

        if (movingLoop && movingLoop.isPlaying) movingLoop.Stop();

        animRoutine = null;

        if (!opening)
            openedFullThisCycle = false;

        RaiseDoorEvent(opening ? "opened" : "closed");
    }

    private void UpdateNavObstacle() //method generated by ChatGPT
    {
        if (navObstacle != null)
        {
            bool shouldBlock;

            if (isLocked)
            {
                shouldBlock = lockedAlwaysBlocks ? true : !isOpen;
            }
            else
            {
                // Only block when manual override forces it closed.
                // If sensor-controlled, never block.
                shouldBlock = manualOverride && !isOpen;
            }

            navObstacle.enabled = shouldBlock;
        }

        UpdateIndicatorLight(); // ✅ keep it in one place
    }

    private void UpdateIndicatorLight() //method generated by ChatGPT
    {
        if (indicatorLight == null) return;

        // Priority 1: locked = red
        if (isLocked)
        {
            indicatorLight.color = lockedColor;
            return;
        }

        // Sensor mode (manual override OFF) = green
        if (!manualOverride)
        {
            indicatorLight.color = sensorColor;
            return;
        }

        // Manual override:
        // open = green, closed = orange
        indicatorLight.color = isOpen ? sensorColor : manualClosedColor;
    }

    private void RaiseDoorEvent(string action) //method generated by ChatGPT
    {
        if (!raiseMissionEvents) return;
        GameEvents.Raise($"door.{action}.{NormalizedId}", this);
    }

    public void SetOpenInstant(bool open) //method generated by ChatGPT for checkpoint system
    {
        if (panel == null) return;

        if (animRoutine != null) StopCoroutine(animRoutine);
        if (pendingCloseRoutine != null) StopCoroutine(pendingCloseRoutine);
        animRoutine = null;
        pendingCloseRoutine = null;

        isOpen = open;
        panel.localPosition = open ? openLocalPos : closedLocalPos;

        if (movingLoop && movingLoop.isPlaying) movingLoop.Stop();

        UpdateNavObstacle(); // ✅ includes light update
    }

    public void SetManualOverride(bool value)
    {
        manualOverride = value;

        if (manualOverride)
        {
            if (pendingCloseRoutine != null)
            {
                StopCoroutine(pendingCloseRoutine);
                pendingCloseRoutine = null;
            }
        }

        UpdateNavObstacle(); //method generated by ChatGPT
    }
    public void RebuildOccupantsFromSensors() //method generated by ChatGPT for checkpoint system
    {
        occupants.Clear();

        // Find all DoorSensor triggers belonging to this door
        var sensors = GetComponentsInChildren<DoorSensor>(true);
        foreach (var s in sensors)
        {
            if (!s) continue;
            var c = s.GetComponent<Collider>();
            if (!c) continue;

            var b = c.bounds;
            var hits = Physics.OverlapBox(b.center, b.extents, c.transform.rotation, actorMask, QueryTriggerInteraction.Collide);

            foreach (var h in hits)
            {
                if (!h) continue;
                if (h == c) continue;

                if (IsActor(h.gameObject))
                    occupants.Add(h);
            }
        }

        // If we’re in sensor mode and unlocked, enforce correct open/close state
        if (!manualOverride && !isLocked)
        {
            if (OccupantCount > 0)
            {
                // If ANY occupant is not small -> open full
                bool anyFull = false;
                foreach (var col in occupants)
                {
                    if (col && !IsSmallActor(col.gameObject)) { anyFull = true; break; }
                }

                openedFullThisCycle = anyFull;
                OpenNowTo(anyFull ? openLocalPos : smallOpenLocalPos,
                          anyFull ? openTime : smallOpenTime);
            }
            else
            {
                // nobody inside; if door is open, schedule close normally
                if (isOpen) ScheduleClose();
            }
        }
    }


#if UNITY_EDITOR
//gizmos generated by ChatGPT
    private void OnDrawGizmosSelected()
    {
        if (panel != null)
        {
            var closed = panel.localPosition;
            var open = closed + Vector3.up * openOffsetY;
            Gizmos.color = Color.cyan;
            Gizmos.matrix = panel.parent ? panel.parent.localToWorldMatrix : Matrix4x4.identity;
            Gizmos.DrawLine(closed, open);
            Gizmos.DrawSphere(open, 0.05f);
        }

        if (blockingCheck != null)
        {
            Gizmos.color = new Color(1f, 0.6f, 0f, 0.25f);
            var m = blockingCheck.transform;
            var center = m.TransformPoint(blockingCheck.center);
            var size = Vector3.Scale(blockingCheck.size, m.lossyScale);
            Gizmos.matrix = Matrix4x4.TRS(center, m.rotation, size);
            Gizmos.DrawCube(Vector3.zero, Vector3.one);
        }
    }
#endif
}
