using UnityEngine;

[RequireComponent(typeof(Collider))]
public class DoorSensor : MonoBehaviour
{
    [SerializeField] private DoorSlideUp door;

    private void Reset() //method generated by ChatGPT
    {
        if (GetComponent<Collider>() is Collider c)
            c.isTrigger = true;
        if (door == null) door = GetComponentInParent<DoorSlideUp>();
    }

    private void OnTriggerEnter(Collider other)
    {
        if (door) door.SensorEnter(other);
    }

    private void OnTriggerExit(Collider other)
    {
        if (door) door.SensorExit(other);
    }
}
