using System.Collections;
using UnityEngine;
using UnityEngine.AI;

public class ExtendableBridge : MonoBehaviour
{
    [Header("Bridge ID")]
    [Tooltip("Unique name, e.g. B-32, B-35, etc.")]
    public string bridgeId = "B-01";

    [Header("Moving Part")]
    [Tooltip("The part of the bridge that actually moves")]
    [SerializeField] private Transform movingPart;

    [Header("Positions (local)")]
    [SerializeField] private Vector3 retractedLocalPosition;
    [SerializeField] private Vector3 extendedLocalPosition;

    [Header("Editor Baking")]
    [Tooltip("Force bridge to appear extended in edit mode")]
    [SerializeField] private bool forceExtendedInEditMode = true;

    [Header("Animation")]
    [SerializeField] private float extendTime = 1.0f;
    [SerializeField] private AnimationCurve extendCurve = AnimationCurve.EaseInOut(0, 0, 1, 1);

    [Header("State")]
    [SerializeField] private bool startExtended = false;

    [Header("Gizmo Tip Offset")]
    [Tooltip("Local offset from movingPart pivot to the TIP of the bridge (used only for gizmos & noise origin).")]
    [SerializeField] private Vector3 tipLocalOffset = Vector3.zero;

    [Header("Movement Sound & Noise")]
    [SerializeField] private AudioSource moveAudioSource;
    [SerializeField] private bool playSoundOnExtend = true;
    [SerializeField] private bool playSoundOnRetract = true;

    [SerializeField] private float movementNoiseLoudness = 10f;
    [SerializeField] private float movementNoiseInterval = 0.25f;
    [SerializeField] private bool useTipAsNoiseOrigin = true;

    [Header("End Movement Sound")]
    [SerializeField] private AudioSource endExtendSound;
    [SerializeField] private AudioSource endRetractSound;

    [Header("NavMesh")]
    [Tooltip("Optional obstacle to block the monster when the bridge is NOT fully extended (closed OR opening OR closing).")]
    [SerializeField] private NavMeshObstacle navMeshObstacle;

    [Header("Ledge Blockers (Player Safety)")]
    [Tooltip("Collider on one ledge that blocks the player from falling when bridge is not fully extended.")]
    [SerializeField] private Collider ledgeBlockerA;
    [Tooltip("Collider on the other ledge that blocks the player from falling when bridge is not fully extended.")]
    [SerializeField] private Collider ledgeBlockerB;

    [Header("Occupancy (Can't retract if someone is on it)")]
    [Tooltip("Trigger volume covering the bridge surface. If an actor is inside, bridge cannot retract.")]
    [SerializeField] private BoxCollider occupancyTrigger;
    [SerializeField] private LayerMask actorMask = ~0;
    [Tooltip("If true, Retract() will wait until clear instead of doing nothing.")]
    [SerializeField] private bool retractWhenClear = true;
    [SerializeField] private float retractRetryInterval = 0.2f;

    private Coroutine moveRoutine;
    private Coroutine pendingRetractRoutine;

    private bool isExtended;
    public bool IsExtended => isExtended;

    private bool isMoving;

    private void Reset() //method generated by ChatGPT
    {
        movingPart = transform;
        retractedLocalPosition = Vector3.zero;
        extendedLocalPosition = Vector3.right * 3f;
        extendTime = 1.0f;
    }

    private void Awake()
    {
        if (movingPart == null)
            movingPart = transform;

        movingPart.localPosition = startExtended ? extendedLocalPosition : retractedLocalPosition;
        isExtended = startExtended;
        isMoving = false;

        ApplyBlockersAndObstacle();
    }

    private void OnEnable()
    {
        BridgeRegistry.Register(this);
    }

    private void OnDisable()
    {
        BridgeRegistry.Unregister(this);
    }

    public string NormalizedId => BridgeRegistry.NormalizeBridgeId(bridgeId);

    public void Extend()
    {
        if (isMoving) return;
        if (isExtended) return;

        StartMove(true);
    }

    public void Retract()
    {
        if (isMoving) return;
        if (!isExtended) return;

        // Can't retract if someone is on it
        if (IsOccupied())
        {
            if (retractWhenClear) 
            {
                if (pendingRetractRoutine == null)
                    pendingRetractRoutine = StartCoroutine(RetractWhenClearRoutine());
            }
            return;
        }

        StartMove(false);
    }

    public void Toggle()
    {
        if (isExtended) Retract();
        else Extend();
    }

    private IEnumerator RetractWhenClearRoutine()
    {
        while (IsOccupied())
            yield return new WaitForSeconds(retractRetryInterval);

        pendingRetractRoutine = null;
        Retract();
    }

    private void StartMove(bool toExtended)
    {
        if (pendingRetractRoutine != null)
        {
            StopCoroutine(pendingRetractRoutine);
            pendingRetractRoutine = null;
        }

        if (moveRoutine != null)
            StopCoroutine(moveRoutine);

        moveRoutine = StartCoroutine(MoveBridge(toExtended));
    }

    private IEnumerator MoveBridge(bool toExtended)
    {
        isMoving = true;

        ApplyBlockersAndObstacle(true); //method generated with ChatGPT

        Vector3 start = movingPart.localPosition;
        Vector3 end = toExtended ? extendedLocalPosition : retractedLocalPosition;

        float t = 0f;
        float duration = Mathf.Max(0.01f, extendTime);

        bool shouldPlaySound =
            (toExtended && playSoundOnExtend) ||
            (!toExtended && playSoundOnRetract);

        if (shouldPlaySound && moveAudioSource != null)
        {
            moveAudioSource.Stop();
            moveAudioSource.Play();
        }

        float noiseTimer = 0f;

        while (t < 1f)
        {
            t += Time.deltaTime / duration;
            float k = extendCurve.Evaluate(Mathf.Clamp01(t));
            movingPart.localPosition = Vector3.Lerp(start, end, k);

            noiseTimer += Time.deltaTime;
            if (noiseTimer >= movementNoiseInterval)
            {
                noiseTimer = 0f;

                Vector3 origin = useTipAsNoiseOrigin
                    ? movingPart.TransformPoint(tipLocalOffset)
                    : movingPart.position;

                Noise.MakeNoise(moveAudioSource.transform.position, movementNoiseLoudness, gameObject);
            }

            yield return null;
        }

        movingPart.localPosition = end;
        isExtended = toExtended;
        isMoving = false;
        moveRoutine = null;


        ApplyBlockersAndObstacle(); //method generated with chatGPT

        if (moveAudioSource != null && moveAudioSource.isPlaying)
            moveAudioSource.Stop();

        if (toExtended)
        {
            if (endExtendSound != null) { endExtendSound.Stop(); endExtendSound.Play(); }
        }
        else
        {
            if (endRetractSound != null) { endRetractSound.Stop(); endRetractSound.Play(); }
        }
    }

    /// <summary>
    /// Applies:
    /// - Ledge blockers: ON unless fully extended.
    /// - NavMeshObstacle: ON unless fully extended. (So monster can't path over while closed OR opening.)
    /// </summary>
    private void ApplyBlockersAndObstacle(bool movingAssumeNotExtended = false) //method generated with Chat GPT
    {
        bool fullyExtended = isExtended && !isMoving && !movingAssumeNotExtended;

        // Player safety blockers: active unless fully extended
        bool blockersOn = !fullyExtended;
        if (ledgeBlockerA) ledgeBlockerA.enabled = blockersOn;
        if (ledgeBlockerB) ledgeBlockerB.enabled = blockersOn;

        // Monster safety/pathing: obstacle enabled unless fully extended
        if (navMeshObstacle != null)
        {
            navMeshObstacle.enabled = !fullyExtended;
            // Make sure carving is enabled in the obstacle component if you rely on it.
        }
    }

    private bool IsOccupied() //method generated with ChatGPT
    {
        if (occupancyTrigger == null) return false;

        // Build an OverlapBox matching the trigger volume in world space
        Transform t = occupancyTrigger.transform;

        Vector3 worldCenter = t.TransformPoint(occupancyTrigger.center);
        Vector3 worldHalfExtents = Vector3.Scale(occupancyTrigger.size * 0.5f, t.lossyScale);

        Collider[] hits = Physics.OverlapBox(
            worldCenter,
            worldHalfExtents,
            t.rotation,
            actorMask,
            QueryTriggerInteraction.Collide // because occupancyTrigger is a trigger volume
        );

        // Filter out our own colliders if needed (optional)
        for (int i = 0; i < hits.Length; i++)
        {
            if (hits[i] == null) continue;

            // Ignore self
            if (hits[i].transform.IsChildOf(transform)) continue;

            return true;
        }

        return false;
    }
    public void SetExtendedInstant(bool extended) //method generated with Chat GPT
    {
        if (movingPart == null) movingPart = transform;

        if (moveRoutine != null) StopCoroutine(moveRoutine);
        if (pendingRetractRoutine != null) StopCoroutine(pendingRetractRoutine);
        moveRoutine = null;
        pendingRetractRoutine = null;

        isMoving = false;
        isExtended = extended;
        movingPart.localPosition = extended ? extendedLocalPosition : retractedLocalPosition;

        ApplyBlockersAndObstacle();

        if (moveAudioSource != null && moveAudioSource.isPlaying) moveAudioSource.Stop();
    }


#if UNITY_EDITOR
    private void OnValidate()
    {
        if (movingPart == null) movingPart = transform;

        if (!Application.isPlaying && forceExtendedInEditMode && movingPart != null)
        {
            movingPart.localPosition = extendedLocalPosition;
        }
    }
#endif

#if UNITY_EDITOR
//gizmos generated with ChatGPT
    private void OnDrawGizmos()
    {
        if (movingPart == null)
            movingPart = transform;

        Transform parent = movingPart.parent;

        Vector3 worldRetractedTip = parent
            ? parent.TransformPoint(retractedLocalPosition + tipLocalOffset)
            : retractedLocalPosition + tipLocalOffset;

        Vector3 worldExtendedTip = parent
            ? parent.TransformPoint(extendedLocalPosition + tipLocalOffset)
            : extendedLocalPosition + tipLocalOffset;

        Gizmos.color = Color.yellow;
        Gizmos.DrawWireCube(worldRetractedTip, Vector3.one * 0.17f);

        Gizmos.color = Color.green;
        Gizmos.DrawWireCube(worldExtendedTip, Vector3.one * 0.17f);

        Gizmos.color = Color.cyan;
        Gizmos.DrawLine(worldRetractedTip, worldExtendedTip);

        Vector3 dir = (worldExtendedTip - worldRetractedTip).normalized;
        Vector3 right = Vector3.Cross(dir, Vector3.up).normalized;
        float arrowSize = 0.25f;

        Gizmos.DrawLine(worldExtendedTip, worldExtendedTip - dir * arrowSize + right * (arrowSize * 0.5f));
        Gizmos.DrawLine(worldExtendedTip, worldExtendedTip - dir * arrowSize - right * (arrowSize * 0.5f));
        DrawOccupancyGizmo();
        DrawLedgeBlockerGizmo(ledgeBlockerA);
        DrawLedgeBlockerGizmo(ledgeBlockerB);
    }


    private void DrawOccupancyGizmo()
    {
        if (occupancyTrigger == null) return;

        Transform t = occupancyTrigger.transform;

        Vector3 center = t.TransformPoint(occupancyTrigger.center);
        Vector3 size = Vector3.Scale(occupancyTrigger.size, t.lossyScale);

        bool occupied = false;

        // Only check occupancy during play mode
        if (Application.isPlaying)
        {
            occupied = IsOccupied(); 
        }

        Gizmos.color = occupied
            ? new Color(1f, 0f, 0f, 0.9f)   // red = occupied
            : new Color(0f, 1f, 0f, 0.9f);  // green = free

        Gizmos.matrix = Matrix4x4.TRS(center, t.rotation, Vector3.one);
        Gizmos.DrawWireCube(Vector3.zero, size);
        Gizmos.matrix = Matrix4x4.identity;
    }

    private void DrawLedgeBlockerGizmo(Collider col)
    {
        if (col == null) return;
        if (!col.enabled) return;

        Gizmos.color = new Color(1f, 0.5f, 0f, 0.35f); // orange, semi-transparent

        if (col is BoxCollider box)
        {
            Transform t = box.transform;

            Vector3 center = t.TransformPoint(box.center);
            Vector3 size = Vector3.Scale(box.size, t.lossyScale);

            Gizmos.matrix = Matrix4x4.TRS(center, t.rotation, Vector3.one);
            Gizmos.DrawCube(Vector3.zero, size);
            Gizmos.matrix = Matrix4x4.identity;
        }
        else
        {
            // Fallback for non-box colliders
            Gizmos.DrawWireCube(col.bounds.center, col.bounds.size);
        }
    }
#endif
}
